CREATE TABLE document_chunks (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id NUMBER(19) REFERENCES documents(id) ON DELETE CASCADE,
    chunk_index NUMBER(10) DEFAULT 0,
    content CLOB,
    embedding VECTOR(1024, FLOAT32),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

INSERT INTO document_chunks (document_id, chunk_index, content, embedding)
SELECT id, 0, content, embedding
FROM documents
WHERE content IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM document_chunks WHERE document_chunks.document_id = documents.id);

-- 문서당 같은 조각순서 번호가 중복 안 생기게 방지
ALTER TABLE document_chunks ADD CONSTRAINT uq_document_chunk_version UNIQUE (document_id, chunk_index);
