CREATE TABLE chat_sessions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) REFERENCES users(id),
    title VARCHAR2(255),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 제약조건 이름을 명시적으로 지정한다 — Postgres는 이름을 안 주면
-- prompt_sessions_chat_session_id_fkey처럼 예측 가능한 이름을 자동으로
-- 붙여주지만, Oracle은 이름을 안 주면 SYS_C###### 같은 예측 불가능한
-- 이름을 붙인다. V16에서 이 제약조건을 CASCADE로 바꾸며 이름으로 다시
-- 참조하므로 여기서 미리 고정해둔다.
ALTER TABLE prompt_sessions ADD chat_session_id NUMBER(19);
ALTER TABLE prompt_sessions
    ADD CONSTRAINT fk_prompt_sessions_chat_session
    FOREIGN KEY (chat_session_id) REFERENCES chat_sessions(id);
