ALTER TABLE prompt_sessions ADD satisfaction VARCHAR2(10);

CREATE TABLE response_edits (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_session_id NUMBER(19) REFERENCES prompt_sessions(id) ON DELETE CASCADE,
    user_id NUMBER(19) REFERENCES users(id),
    generated_result CLOB NOT NULL,
    user_final_result CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);
