-- PrompTune 초기 스키마 (Oracle Autonomous Database + 네이티브 VECTOR)
-- pgvector의 vector(1024) 컬럼은 Oracle 23ai의 네이티브 VECTOR 타입으로 대체.
-- CREATE EXTENSION 같은 별도 확장 설치가 필요 없음 (Oracle 23ai부터 내장).

-- 사용자
CREATE TABLE users (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) UNIQUE NOT NULL,
    department VARCHAR2(100),
    position VARCHAR2(100),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 선호 설정 (0-2번 온보딩)
CREATE TABLE user_preferences (
    user_id NUMBER(19) PRIMARY KEY REFERENCES users(id),
    speed VARCHAR2(20),         -- 빠르게 / 정확하게
    detail VARCHAR2(20),        -- 간결하게 / 자세하게
    preserve VARCHAR2(20)       -- 원문유지 / 적극보완
);

-- 프롬프트 세션
CREATE TABLE prompt_sessions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) REFERENCES users(id),
    original_text CLOB NOT NULL,
    final_text CLOB,
    task_type VARCHAR2(30),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 행동 로그 (16번 개인화)
CREATE TABLE behavior_logs (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) REFERENCES users(id),
    element VARCHAR2(20),       -- 어떤 요소 추천에 대해
    action VARCHAR2(20),        -- tab(적용) / esc(무시) / alt(대안선택)
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 내부 문서 임베딩 (13번 RAG, Oracle 네이티브 VECTOR)
CREATE TABLE documents (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255),
    content CLOB,
    embedding VECTOR(1024, FLOAT32)     -- BGE-M3 차원
);
