-- Document context integrity and indexing state.
--
-- 1) A document upload and AI-readiness are separate states.
-- 2) A prompt session can reference many documents and the same document can
--    be referenced by many prompt sessions, so attachment memory is N:M.

ALTER TABLE documents ADD (
    index_status VARCHAR2(20) DEFAULT 'UPLOADED' NOT NULL,
    index_error CLOB,
    indexed_at TIMESTAMP
);

-- Existing documents already have document_chunks from the previous indexer.
-- Backfill their readiness from the actual stored data rather than pretending
-- every historical document is merely UPLOADED.
UPDATE documents d
SET index_status = CASE
        WHEN EXISTS (
            SELECT 1
            FROM document_chunks dc
            WHERE dc.document_id = d.id
              AND dc.embedding IS NOT NULL
        ) THEN 'READY'
        WHEN EXISTS (
            SELECT 1
            FROM document_chunks dc
            WHERE dc.document_id = d.id
        ) THEN 'TEXT_READY'
        ELSE 'UPLOADED'
    END,
    indexed_at = CASE
        WHEN EXISTS (
            SELECT 1
            FROM document_chunks dc
            WHERE dc.document_id = d.id
        ) THEN COALESCE(d.indexed_at, SYSTIMESTAMP)
        ELSE d.indexed_at
    END;

-- 원본은 재실행 대비로 DROP CONSTRAINT IF EXISTS 후 재생성했지만, 이 제약조건은
-- 이 마이그레이션에서 처음 추가되는 것이라(V1~V25 어디에도 없음) Oracle
-- 버전에서는 DROP 없이 바로 추가하면 된다.
ALTER TABLE documents
    ADD CONSTRAINT ck_documents_index_status
    CHECK (index_status IN ('UPLOADED', 'INDEXING', 'TEXT_READY', 'READY', 'FAILED'));

CREATE TABLE prompt_session_documents (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_session_id NUMBER(19) NOT NULL
        REFERENCES prompt_sessions(id) ON DELETE CASCADE,
    document_id NUMBER(19) NOT NULL
        REFERENCES documents(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_prompt_session_document
        UNIQUE (prompt_session_id, document_id)
);

CREATE INDEX idx_psd_prompt_session_id
    ON prompt_session_documents(prompt_session_id);

CREATE INDEX idx_psd_document_id
    ON prompt_session_documents(document_id);

-- Preserve all attachment relations recorded by V25 before the N:M table
-- existed. Keep documents.prompt_session_id for backward compatibility during
-- this migration phase; application reads/writes use the join table now.
-- (ON CONFLICT DO NOTHING → Oracle MERGE)
MERGE INTO prompt_session_documents tgt
USING (
    SELECT d.prompt_session_id AS prompt_session_id, d.id AS document_id
    FROM documents d
    WHERE d.prompt_session_id IS NOT NULL
) src
ON (tgt.prompt_session_id = src.prompt_session_id AND tgt.document_id = src.document_id)
WHEN NOT MATCHED THEN
    INSERT (prompt_session_id, document_id)
    VALUES (src.prompt_session_id, src.document_id);
