-- PrompTune 목업 시드 데이터
-- Flyway V2: V1(스키마) 다음에 자동 실행됨. 순서 보장됨.

-- 샘플 사용자 (프론트가 userId=1로 호출)
-- ON CONFLICT (id) DO NOTHING → Oracle은 MERGE로 동일한 "이미 있으면 건너뛰기"를 구현.
MERGE INTO users tgt
USING (SELECT 1 dummy FROM dual) src
ON (tgt.id = 1)
WHEN NOT MATCHED THEN
    INSERT (id, email, department, position)
    VALUES (1, 'byeonghwan@promptune.dev', '마케팅팀', '사원');

-- 선호 설정 (0-2번 온보딩 완료 상태)
MERGE INTO user_preferences tgt
USING (SELECT 1 dummy FROM dual) src
ON (tgt.user_id = 1)
WHEN NOT MATCHED THEN
    INSERT (user_id, speed, detail, preserve)
    VALUES (1, '정확하게', '자세하게', '적극보완');

-- 내부 문서 샘플 (13번 RAG용). embedding은 목업이라 0벡터로 채움.
-- 실제로는 승연이 BGE-M3로 임베딩 생성.
-- array_fill(0, ARRAY[1024])::vector → Oracle은 array_fill이 없어서
-- LISTAGG/CONNECT BY로 '0,0,...,0'(1024개) 문자열을 만들어 TO_VECTOR로 변환한다.
INSERT INTO documents (title, content, embedding) VALUES (
    '휴가 규정 안내',
    '연차는 입사 1년 후 15일 부여되며, 반차는 오전/오후로 나뉜다.',
    TO_VECTOR('[' || (SELECT LISTAGG('0', ',') WITHIN GROUP (ORDER BY LEVEL) FROM dual CONNECT BY LEVEL <= 1024) || ']')
);
INSERT INTO documents (title, content, embedding) VALUES (
    '경비 처리 지침',
    '경비 신청은 지출 후 7일 이내에 영수증과 함께 제출한다.',
    TO_VECTOR('[' || (SELECT LISTAGG('0', ',') WITHIN GROUP (ORDER BY LEVEL) FROM dual CONNECT BY LEVEL <= 1024) || ']')
);
INSERT INTO documents (title, content, embedding) VALUES (
    '보고서 작성 표준',
    '사내 보고서는 요약-본문-결론 순으로 작성하며 3장을 넘기지 않는다.',
    TO_VECTOR('[' || (SELECT LISTAGG('0', ',') WITHIN GROUP (ORDER BY LEVEL) FROM dual CONNECT BY LEVEL <= 1024) || ']')
);

-- 시퀀스 보정 (수동 id 삽입 후)
-- Oracle IDENTITY 컬럼에는 setval이 없다. 다음 자동 생성값이 방금 수동으로
-- 넣은 id(=1)와 겹치지 않도록 시작값을 MAX(id)+1로 재설정한다.
DECLARE
    v_next NUMBER;
BEGIN
    SELECT NVL(MAX(id), 0) + 1 INTO v_next FROM users;
    EXECUTE IMMEDIATE 'ALTER TABLE users MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_next || ')';
END;
/
