CREATE TABLE personalization_score (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL REFERENCES users(id),
    element VARCHAR2(20) NOT NULL,
    accept_count NUMBER(10) DEFAULT 0,
    dismiss_count NUMBER(10) DEFAULT 0,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    UNIQUE(user_id, element)
);
