CREATE TABLE receiver_profile (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL REFERENCES users(id),
    receiver_name VARCHAR2(100) NOT NULL,
    relationship VARCHAR2(50),
    preferred_tone VARCHAR2(50),
    avg_length NUMBER(10),
    apply_rate NUMBER(5,2),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
);
