CREATE TABLE model_usage_log (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR2(30),
    endpoint VARCHAR2(50),
    response_time_ms NUMBER(10),
    status VARCHAR2(20),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);
